In [1]:
import pandas as pd

In [2]:
import pandas as pd

prostate_cancer_required_columns_21 = pd.read_csv("prostate_cancer_required_columns_21.csv")

In [3]:
prostate_cancer_required_columns_21.describe

<bound method NDFrame.describe of       AGEP_A  BMICAT_A  DIBEV_A  SMKEV_A  SMKCIGST_A  CHLEV_A  ECIGEV_A  \
0         65         3        2        2           4        1         2
1         69         4        2        2           4        1         2
2         76         3        2        2           4        1         2
3         75         4        1        2           4        2         2
4         76         4        2        1           3        1         2
...      ...       ...      ...      ...         ...      ...       ...
1541      72         3        2        2           4        1         2
1542      59         4        1        1           1        1         1
1543      71         3        2        1           1        2         1
1544      48         3        2        2           4        2         2
1545      76         4        1        1           3        1         2

      SMKECIGST_A  COPDEV_A  ASEV_A  ...  EMDWRKCAT1_A  FDSBALANCE_A  \
0               3         2       2  ...           NaN             3
1               3         2       1  ...           NaN             3
2               3         2       2  ...           1.0             3
3               3         2       2  ...           NaN             3
4               3         2       2  ...           NaN             3
...           ...       ...     ...  ...           ...           ...
1541            3         2       2  ...           NaN             3
1542            2         2       2  ...           NaN             2
1543            2         2       2  ...           1.0             3
1544            3         2       2  ...           5.0             3
1545            3         2       2  ...           NaN             3

      FDSLESS_A  FDSHUNGRY_A  FDSWEIGHT_A  HOUTENURE_A  POVRATTC_A  \
0           NaN          NaN          NaN            1        2.46
1           NaN          NaN          NaN            1        4.79
2           NaN          NaN          NaN            1        2.86
3           NaN          NaN          NaN            1        3.22
4           NaN          NaN          NaN            1        7.66
...         ...          ...          ...          ...         ...
1541        NaN          NaN          NaN            1        6.39
1542        2.0          2.0          2.0            2        2.76
1543        NaN          NaN          NaN            2        4.60
1544        NaN          NaN          NaN            1        8.94
1545        NaN          NaN          NaN            1        4.47

      FDSRUNOUT_A  FDSLAST_A  HISP_A
0               3          3       2
1               3          3       2
2               3          3       2
3               3          3       2
4               3          3       2
...           ...        ...     ...
1541            3          3       2
1542            3          3       2
1543            3          3       2
1544            3          3       2
1545            3          3       2

[1546 rows x 33 columns]>

In [4]:
prostate_cancer_required_columns_21.sample(10)

,AGEP_A,BMICAT_A,DIBEV_A,SMKEV_A,SMKCIGST_A,CHLEV_A,ECIGEV_A,SMKECIGST_A,COPDEV_A,ASEV_A,...,EMDWRKCAT1_A,FDSBALANCE_A,FDSLESS_A,FDSHUNGRY_A,FDSWEIGHT_A,HOUTENURE_A,POVRATTC_A,FDSRUNOUT_A,FDSLAST_A,HISP_A
259,65,3,2,2,4,2,2,3,2,1,...,4.0,3,NaN,NaN,NaN,1,4.15,3,3,2
726,68,3,2,2,4,2,2,3,2,2,...,1.0,3,NaN,NaN,NaN,1,3.62,3,3,2
690,85,3,2,2,4,1,2,3,2,2,...,NaN,3,NaN,NaN,NaN,1,3.99,3,3,2
326,62,4,1,2,4,1,2,3,2,2,...,1.0,3,NaN,NaN,NaN,1,4.21,3,3,2
1083,51,2,2,2,4,1,1,2,2,1,...,1.0,3,NaN,NaN,NaN,1,11.00,3,3,2
891,69,2,2,2,4,2,2,3,2,2,...,5.0,3,NaN,NaN,NaN,2,1.20,3,3,2
713,37,3,2,2,4,2,2,3,2,2,...,1.0,3,NaN,NaN,NaN,2,1.56,3,3,2
1087,78,3,2,1,3,1,2,3,1,2,...,NaN,3,NaN,NaN,NaN,1,2.57,3,3,2
1284,56,3,2,1,3,1,2,3,2,1,...,1.0,3,NaN,NaN,NaN,2,7.40,3,3,2
930,85,2,2,1,3,1,2,3,2,2,...,NaN,3,NaN,NaN,NaN,2,4.83,3,3,2

In [5]:
prostate_cancer_required_columns_21.isna()

,AGEP_A,BMICAT_A,DIBEV_A,SMKEV_A,SMKCIGST_A,CHLEV_A,ECIGEV_A,SMKECIGST_A,COPDEV_A,ASEV_A,...,EMDWRKCAT1_A,FDSBALANCE_A,FDSLESS_A,FDSHUNGRY_A,FDSWEIGHT_A,HOUTENURE_A,POVRATTC_A,FDSRUNOUT_A,FDSLAST_A,HISP_A
0,False,False,False,False,False,False,False,False,False,False,...,True,False,True,True,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,False,True,True,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,True,False,True,True,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,True,False,True,True,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1541,False,False,False,False,False,False,False,False,False,False,...,True,False,True,True,True,False,False,False,False,False
1542,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
1543,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,False,False,False,False,False
1544,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,False,False,False,False,False
1545,False,False,False,False,False,False,False,False,False,False,...,True,False,True,True,True,False,False,False,False,False

In [6]:
column_list = prostate_cancer_required_columns_21.columns.tolist()
print(column_list)

['AGEP_A', 'BMICAT_A', 'DIBEV_A', 'SMKEV_A', 'SMKCIGST_A', 'CHLEV_A', 'ECIGEV_A', 'SMKECIGST_A', 'COPDEV_A', 'ASEV_A', 'SASPPHISP_A', 'HYPEV_A', 'CHDEV_A', 'STREV_A', 'BREASCAN_A', 'SEX_A', 'PROSTCAN_A', 'HISPALLP_A', 'HISDETP_A', 'RACEALLP_A', 'EDUCP_A', 'URBRRL', 'K6SPD_A', 'EMDWRKCAT1_A', 'FDSBALANCE_A', 'FDSLESS_A', 'FDSHUNGRY_A', 'FDSWEIGHT_A', 'HOUTENURE_A', 'POVRATTC_A', 'FDSRUNOUT_A', 'FDSLAST_A', 'HISP_A']

## DROP SEX_A

In [7]:
import pandas as pd

# Assuming you have a DataFrame named 'prostate_cancer_required_columns_21'
prostate_cancer_required_columns_21 = pd.read_csv("prostate_cancer_required_columns_21.csv")

# Specify the list of variables (columns) you want to remove
columns_to_remove = ['SEX_A', 'SASPPHISP_A', 'FDSLESS_A', 'FDSHUNGRY_A', 'FDSWEIGHT_A', 'EMDWRKCAT1_A']

# Use the drop method to remove the specified columns
prostate_cancer_required_columns_21 = prostate_cancer_required_columns_21.drop(columns=columns_to_remove, axis=1)

# Check and list out the number of missing values in each variable
missing_values = prostate_cancer_required_columns_21.isna().sum()

# Print the result
print(missing_values)

AGEP_A          0
BMICAT_A        0
DIBEV_A         0
SMKEV_A         0
SMKCIGST_A      0
CHLEV_A         0
ECIGEV_A        0
SMKECIGST_A     0
COPDEV_A        0
ASEV_A          0
HYPEV_A         0
CHDEV_A         0
STREV_A         0
BREASCAN_A      0
PROSTCAN_A      0
HISPALLP_A      0
HISDETP_A       0
RACEALLP_A      0
EDUCP_A         0
URBRRL          0
K6SPD_A         0
FDSBALANCE_A    0
HOUTENURE_A     0
POVRATTC_A      0
FDSRUNOUT_A     0
FDSLAST_A       0
HISP_A          0
dtype: int64

In [8]:
column_list = prostate_cancer_required_columns_21.columns.tolist()
print(column_list)

['AGEP_A', 'BMICAT_A', 'DIBEV_A', 'SMKEV_A', 'SMKCIGST_A', 'CHLEV_A', 'ECIGEV_A', 'SMKECIGST_A', 'COPDEV_A', 'ASEV_A', 'HYPEV_A', 'CHDEV_A', 'STREV_A', 'BREASCAN_A', 'PROSTCAN_A', 'HISPALLP_A', 'HISDETP_A', 'RACEALLP_A', 'EDUCP_A', 'URBRRL', 'K6SPD_A', 'FDSBALANCE_A', 'HOUTENURE_A', 'POVRATTC_A', 'FDSRUNOUT_A', 'FDSLAST_A', 'HISP_A']

## MODEL DEVELOPMENT

In [9]:
import pandas as pd
pd.set_option('display.max_columns', None)
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [10]:
print("lenght of data", len(prostate_cancer_required_columns_21))
prostate_cancer_required_columns_21.head()

lenght of data 1546

,AGEP_A,BMICAT_A,DIBEV_A,SMKEV_A,SMKCIGST_A,CHLEV_A,ECIGEV_A,SMKECIGST_A,COPDEV_A,ASEV_A,HYPEV_A,CHDEV_A,STREV_A,BREASCAN_A,PROSTCAN_A,HISPALLP_A,HISDETP_A,RACEALLP_A,EDUCP_A,URBRRL,K6SPD_A,FDSBALANCE_A,HOUTENURE_A,POVRATTC_A,FDSRUNOUT_A,FDSLAST_A,HISP_A
0,65,3,2,2,4,1,2,3,2,2,1,2,2,2.0,2.0,2,3,1,8,3,2,3,1,2.46,3,3,2
1,69,4,2,2,4,1,2,3,2,1,1,2,2,2.0,2.0,2,3,1,8,3,2,3,1,4.79,3,3,2
2,76,3,2,2,4,1,2,3,2,2,1,2,2,2.0,2.0,2,3,1,5,1,2,3,1,2.86,3,3,2
3,75,4,1,2,4,2,2,3,2,2,1,1,2,2.0,2.0,2,3,1,9,1,2,3,1,3.22,3,3,2
4,76,4,2,1,3,1,2,3,2,2,1,2,2,2.0,1.0,2,3,1,10,3,2,3,1,7.66,3,3,2

In [11]:
prostate_cancer_required_columns_21.describe()

,AGEP_A,BMICAT_A,DIBEV_A,SMKEV_A,SMKCIGST_A,CHLEV_A,ECIGEV_A,SMKECIGST_A,COPDEV_A,ASEV_A,HYPEV_A,CHDEV_A,STREV_A,BREASCAN_A,PROSTCAN_A,HISPALLP_A,HISDETP_A,RACEALLP_A,EDUCP_A,URBRRL,K6SPD_A,FDSBALANCE_A,HOUTENURE_A,POVRATTC_A,FDSRUNOUT_A,FDSLAST_A,HISP_A
count,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000,1546.000000
mean,69.248383,3.015524,1.820181,1.556274,3.355110,1.487710,2.020699,3.009056,1.901035,1.892626,1.390039,1.842173,1.933376,2.040103,1.754851,2.113842,2.952135,1.266494,6.459250,2.463777,2.131307,3.067270,1.358991,4.946300,3.060155,3.075032,1.954722
std,12.235463,0.848996,0.428749,1.004071,1.143448,0.598956,0.881062,0.895105,0.354224,0.363528,0.487917,0.560565,0.367038,0.535783,0.716919,0.670200,0.432093,1.030350,5.307986,1.034196,0.982812,0.851043,1.173538,3.112311,0.855746,0.838899,0.207981
min,18.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000
25%,63.000000,2.000000,2.000000,1.000000,3.000000,1.000000,2.000000,3.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,1.000000,2.000000,3.000000,1.000000,4.000000,2.000000,2.000000,3.000000,1.000000,2.480000,3.000000,3.000000,2.000000
50%,71.000000,3.000000,2.000000,1.000000,3.000000,1.000000,2.000000,3.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,1.000000,7.000000,3.000000,2.000000,3.000000,1.000000,4.150000,3.000000,3.000000,2.000000
75%,78.000000,4.000000,2.000000,2.000000,4.000000,2.000000,2.000000,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,1.000000,8.000000,3.000000,2.000000,3.000000,1.000000,6.720000,3.000000,3.000000,2.000000
max,97.000000,9.000000,9.000000,8.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,2.000000,9.000000,9.000000,9.000000,9.000000,7.000000,9.000000,8.000000,99.000000,4.000000,8.000000,8.000000,8.000000,11.000000,8.000000,8.000000,2.000000

In [12]:
prostate_cancer_required_columns_21.dtypes

AGEP_A            int64
BMICAT_A          int64
DIBEV_A           int64
SMKEV_A           int64
SMKCIGST_A        int64
CHLEV_A           int64
ECIGEV_A          int64
SMKECIGST_A       int64
COPDEV_A          int64
ASEV_A            int64
HYPEV_A           int64
CHDEV_A           int64
STREV_A           int64
BREASCAN_A      float64
PROSTCAN_A      float64
HISPALLP_A        int64
HISDETP_A         int64
RACEALLP_A        int64
EDUCP_A           int64
URBRRL            int64
K6SPD_A           int64
FDSBALANCE_A      int64
HOUTENURE_A       int64
POVRATTC_A      float64
FDSRUNOUT_A       int64
FDSLAST_A         int64
HISP_A            int64
dtype: object

In [13]:
columns_to_exclude = ["AGEP_P"]
a
# Get a list of columns to convert to categorical data type
columns_to_convert = [col for col in prostate_cancer_required_columns_21.columns if col not in columns_to_exclude]

# Convert the selected columns to categorical data type
prostate_cancer_required_columns_21[columns_to_convert] = prostate_cancer_required_columns_21[columns_to_convert].astype("category")

In [14]:
prostate_cancer_required_columns_21.dtypes

AGEP_A          category
BMICAT_A        category
DIBEV_A         category
SMKEV_A         category
SMKCIGST_A      category
CHLEV_A         category
ECIGEV_A        category
SMKECIGST_A     category
COPDEV_A        category
ASEV_A          category
HYPEV_A         category
CHDEV_A         category
STREV_A         category
BREASCAN_A      category
PROSTCAN_A      category
HISPALLP_A      category
HISDETP_A       category
RACEALLP_A      category
EDUCP_A         category
URBRRL          category
K6SPD_A         category
FDSBALANCE_A    category
HOUTENURE_A     category
POVRATTC_A      category
FDSRUNOUT_A     category
FDSLAST_A       category
HISP_A          category
dtype: object

In [15]:
prostate_cancer_required_columns_21 = prostate_cancer_required_columns_21.astype({"AGEP_A":'int64'})

In [16]:
prostate_cancer_required_columns_21.dtypes

AGEP_A             int64
BMICAT_A        category
DIBEV_A         category
SMKEV_A         category
SMKCIGST_A      category
CHLEV_A         category
ECIGEV_A        category
SMKECIGST_A     category
COPDEV_A        category
ASEV_A          category
HYPEV_A         category
CHDEV_A         category
STREV_A         category
BREASCAN_A      category
PROSTCAN_A      category
HISPALLP_A      category
HISDETP_A       category
RACEALLP_A      category
EDUCP_A         category
URBRRL          category
K6SPD_A         category
FDSBALANCE_A    category
HOUTENURE_A     category
POVRATTC_A      category
FDSRUNOUT_A     category
FDSLAST_A       category
HISP_A          category
dtype: object

In [17]:
target_mapping = {1: 'Positive', 2: 'Negative', 9: 'Not sure', 7: 'Refused'}
prostate_cancer_required_columns_21['PROSTCAN_A'] = prostate_cancer_required_columns_21['PROSTCAN_A'].replace(target_mapping)

## SPLITTING FEATURED AND TARGET DATA

In [70]:
columns = prostate_cancer_required_columns_21.columns
num_columns = ['AGEP_A', 'URBRRL','BREASCAN_A', 'BMICAT_A', 'EDUCP_A', 'SMKEV_A']
feature_data = prostate_cancer_required_columns_21[num_columns]
target_variable = prostate_cancer_required_columns_21['PROSTCAN_A']

## DATA SPLITTING

In [71]:
prostate_cancer_required_columns_21['PROSTCAN_A'].value_counts()/len(prostate_cancer_required_columns_21)

Negative    0.705692
Positive    0.287840
Not sure    0.005175
Refused     0.001294
Name: PROSTCAN_A, dtype: float64

## Stratifying data

In [78]:
X_train, X_test, y_train, y_test = train_test_split(feature_data, target_variable, test_size=0.2, random_state=42, stratify=target_variable)

In [79]:
X_train, X_test, y_train, y_test = train_test_split(feature_data, target_variable, test_size=0.2, random_state=42, stratify=target_variable)

In [80]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [81]:
model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)
y_train_pred = model.predict(X_train)

C:\Users\HP 10th Gen\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [92]:
print(y_train.unique())  # or y_train.value_counts()

print(prostate_cancer_required_columns_21.columns)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)

pd.get_dummies(y_train)

print(y_train.isnull().sum())

['Negative', 'Positive', 'Not sure', 'Refused']
Categories (4, object): ['Positive', 'Negative', 'Refused', 'Not sure']
Index(['AGEP_A', 'BMICAT_A', 'DIBEV_A', 'SMKEV_A', 'SMKCIGST_A', 'CHLEV_A',
       'ECIGEV_A', 'SMKECIGST_A', 'COPDEV_A', 'ASEV_A', 'HYPEV_A', 'CHDEV_A',
       'STREV_A', 'BREASCAN_A', 'PROSTCAN_A', 'HISPALLP_A', 'HISDETP_A',
       'RACEALLP_A', 'EDUCP_A', 'URBRRL', 'K6SPD_A', 'FDSBALANCE_A',
       'HOUTENURE_A', 'POVRATTC_A', 'FDSRUNOUT_A', 'FDSLAST_A', 'HISP_A'],
      dtype='object')
0

In [91]:
from sklearn.metrics import classification_report
target_names = ['Negative', 'Positive', 'Not sure', 'Refused']
print(classification_report(y_train, y_train_pred, target_names=target_names))

              precision    recall  f1-score   support

    Negative       0.72      0.97      0.83       764
    Positive       1.00      1.00      1.00         6
    Not sure       0.54      0.10      0.16       311
     Refused       1.00      1.00      1.00         1

    accuracy                           0.72      1082
   macro avg       0.81      0.77      0.75      1082
weighted avg       0.67      0.72      0.64      1082

In [77]:
# Fit the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Print the results
print(f"Accuracy: {accuracy:.2f}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 0.70
Confusion Matrix:
[[212   0   7]
 [  0   2   0]
 [ 87   0   2]]
Classification Report:
              precision    recall  f1-score   support

    Negative       0.71      0.97      0.82       219
    Not sure       1.00      1.00      1.00         2
    Positive       0.22      0.02      0.04        89

    accuracy                           0.70       310
   macro avg       0.64      0.66      0.62       310
weighted avg       0.57      0.70      0.60       310

C:\Users\HP 10th Gen\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## ADDING MORE CATEGORICAL VARIABLES

In [26]:
prostate_cancer_required_columns_21

,AGEP_A,BMICAT_A,DIBEV_A,SMKEV_A,SMKCIGST_A,CHLEV_A,ECIGEV_A,SMKECIGST_A,COPDEV_A,ASEV_A,HYPEV_A,CHDEV_A,STREV_A,BREASCAN_A,PROSTCAN_A,HISPALLP_A,HISDETP_A,RACEALLP_A,EDUCP_A,URBRRL,K6SPD_A,FDSBALANCE_A,HOUTENURE_A,POVRATTC_A,FDSRUNOUT_A,FDSLAST_A,HISP_A
0,65,3,2,2,4,1,2,3,2,2,1,2,2,2.0,Negative,2,3,1,8,3,2,3,1,2.46,3,3,2
1,69,4,2,2,4,1,2,3,2,1,1,2,2,2.0,Negative,2,3,1,8,3,2,3,1,4.79,3,3,2
2,76,3,2,2,4,1,2,3,2,2,1,2,2,2.0,Negative,2,3,1,5,1,2,3,1,2.86,3,3,2
3,75,4,1,2,4,2,2,3,2,2,1,1,2,2.0,Negative,2,3,1,9,1,2,3,1,3.22,3,3,2
4,76,4,2,1,3,1,2,3,2,2,1,2,2,2.0,Positive,2,3,1,10,3,2,3,1,7.66,3,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1541,72,3,2,2,4,1,2,3,2,2,1,2,2,2.0,Negative,2,3,1,9,2,2,3,1,6.39,3,3,2
1542,59,4,1,1,1,1,1,2,2,2,1,2,1,2.0,Negative,2,3,1,7,4,1,2,2,2.76,3,3,2
1543,71,3,2,1,1,2,1,2,2,2,1,2,1,2.0,Positive,3,3,2,5,3,2,3,2,4.60,3,3,2
1544,48,3,2,2,4,2,2,3,2,2,1,2,2,2.0,Negative,2,3,1,8,2,2,3,1,8.94,3,3,2
1545,76,4,1,1,3,1,2,3,2,2,1,1,2,2.0,Negative,2,3,1,4,4,2,3,1,4.47,3,3,2

In [27]:
column_list = prostate_cancer_required_columns_21.columns.tolist()
print(column_list)

['AGEP_A', 'BMICAT_A', 'DIBEV_A', 'SMKEV_A', 'SMKCIGST_A', 'CHLEV_A', 'ECIGEV_A', 'SMKECIGST_A', 'COPDEV_A', 'ASEV_A', 'HYPEV_A', 'CHDEV_A', 'STREV_A', 'BREASCAN_A', 'PROSTCAN_A', 'HISPALLP_A', 'HISDETP_A', 'RACEALLP_A', 'EDUCP_A', 'URBRRL', 'K6SPD_A', 'FDSBALANCE_A', 'HOUTENURE_A', 'POVRATTC_A', 'FDSRUNOUT_A', 'FDSLAST_A', 'HISP_A']

In [28]:
#columns = prostate_cancer_required_columns_21.columns
#num_columns = ['AGEP_A', 'URBRRL','BREASCAN_A', 'BMICAT_A', 'EDUCP_A', 'SMKEV_A', 'HISPALLP_A']
#feature_data = prostate_cancer_required_columns_21[num_columns]

In [40]:
target_variable = prostate_cancer_required_columns_21['PROSTCAN_A']

In [41]:
feature_variable = prostate_cancer_required_columns_21.drop(columns=['PROSTCAN_A'])

In [43]:
feature_data_dummy = pd.get_dummies(feature_data, drop_first=True)

In [44]:
feature_data_dummy.head()

,AGEP_A,URBRRL_2,URBRRL_3,URBRRL_4,BREASCAN_A_2.0,BREASCAN_A_7.0,BREASCAN_A_9.0,BMICAT_A_2,BMICAT_A_3,BMICAT_A_4,BMICAT_A_9,EDUCP_A_2,EDUCP_A_3,EDUCP_A_4,EDUCP_A_5,EDUCP_A_6,EDUCP_A_7,EDUCP_A_8,EDUCP_A_9,EDUCP_A_10,EDUCP_A_97,EDUCP_A_99,SMKEV_A_2,SMKEV_A_8,HISPALLP_A_2,HISPALLP_A_3,HISPALLP_A_4,HISPALLP_A_5,HISPALLP_A_6,HISPALLP_A_7
0,65,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0
1,69,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0
2,76,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0
3,75,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0
4,76,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0

In [33]:
target_variable = prostate_cancer_required_columns_21['PROSTCAN_A']